/* GROUP No. 29
		2017A7PS0004P -- SUBHAM KUMAR DASH
		2017A7PS0036P -- RAHUL JHA
		2017A7PS0084P -- ANIRUDDHA JAYANT KARAJGI
		2017A7PS0128P -- MEET KANANI
		2017A7PS0193P -- AYUSH GARG
*/

#include "parser.h"
#include "lexer.h"
#include "ast.h"
#include "semanticAnalyzer.h"
#include "symbolTable.h"
#include "intermediateCode.h"

#include <time.h>

void parse_input_inorder(char *testCaseFile, char *createfile)
{
	Grammar *gm = initialize();
	gm = make_table("grammar.txt", gm);
	FirstAndFollow *firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm, firstFol);
	ParseTable *pt = initializeParseTable();
	populateParseTable(firstFol, gm, pt);
	ParseTree *pTree = parseInputSourceCode(testCaseFile, pt, gm, firstFol);
	printParseTree_inorder(pTree->root, createfile);

	astNode *ast = postOrder_ParseTree(pTree);
}

void parse_input_level_order(char *testCaseFile, char *createfile)
{
	Grammar *gm = initialize();
	gm = make_table("grammar.txt", gm);
	FirstAndFollow *firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm, firstFol);
	ParseTable *pt = initializeParseTable();
	populateParseTable(firstFol, gm, pt);
	ParseTree *pTree = parseInputSourceCode(testCaseFile, pt, gm, firstFol);
	printf("Parse Tree created\n");
	// printParseTree_levelOrder(pTree->root, createfile);
	// printf("Parse Tree printed\n");
	astNode *ast = postOrder_ParseTree(pTree);
	printf("AST Created\n");
	// printAst(ast);
	Table *tb = populateSymbolTable(ast);
	printf("-----------------------------------------Symbol Table Populated--------------------------\n\n");
	// printSymbolTable(tb, "");
	traverse_AST(ast);
	printf("Semantic Analysis done....\n");
	// generate_assembly_code(ast, "code1.asm");
}

void calc_time(char *testCaseFile)
{
	clock_t start_time, end_time;

	double total_CPU_time, total_CPU_time_in_seconds;

	start_time = clock();

	Grammar *gm = initialize();
	gm = make_table("grammar.txt", gm);
	FirstAndFollow *firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm, firstFol);
	ParseTable *pt = initializeParseTable();
	populateParseTable(firstFol, gm, pt);
	ParseTree *pTree = parseInputSourceCode(testCaseFile, pt, gm, firstFol);

	end_time = clock();

	printf("\n");
	printf("Execution Summary\n");
	printf("=================\n");
	printf("Start Time: \t\t\t %lf\n", (double)start_time);
	printf("End Time: \t\t\t %lf\n", (double)end_time);

	total_CPU_time = (double)(end_time - start_time);
	total_CPU_time_in_seconds = total_CPU_time / (double)CLOCKS_PER_SEC;

	printf("Total CPU time: \t\t %8.10f\n", total_CPU_time);
	printf("Total CPU time (in sec): \t %8.10f \n", total_CPU_time_in_seconds);
}

int main(int argc, char *argv[])
{
	printf(
		"\t\t\t\t\tNOTICE\n"
		"\t\t\t\t\t=======\n\n"
		"* FIRST and FOLLOW set automated.\n"
		"* Both lexical and syntax analysis modules have been implemented.\n"
		"* Parse Tree constructed for syntatically correct code.\n"
		"* Parse tree printing is implemented using both Inorder and Level Order Traversal.\n"
		"* Modules work with all the provided testcases including the syntatically incorrect one.\n");

	printf("------------------------------------------------------------------------------------------\n\n");

	if (argc < 3)
	{
		printf(
			"USAGE\n"
			"=====\n\n"
			"The command line argument for execution of the driver should be as follows:\n\n"
			"\t\t$./stage1exe   testcase.txt   parsetreeOutFile.txt\n\n");
		exit(0);
	}

	while (1)
	{
		printf("\nPlease choose an option\n");
		printf("========================= \n\n");
		printf("Press 0 to exit.\n");
		printf("Press 1 to get the comment free code.\n");
		printf("Press 2 to get the token list generated by lexer.\n");
		printf("Press 3 to get the Parse tree in Inorder \n");
		printf("Press 4 to get the Total time elapsed for syntax analysis\n");
		printf("Press 5 to get the Parse tree in Level Order\n");

		int option;
		scanf("%d", &option);

		printf("\n");
		printf("Selected option: %d\n", option);
		printf("----------------------\n\n");
		getchar();

		switch (option)
		{
		case 0:
			printf("Exiting...\n");
			exit(0);
			break;
		case 1:
			removeComments(argv[1]);
			break;
		case 2:
			printTokens(argv[1]);
			break;
		case 3:
			parse_input_inorder(argv[1], argv[2]);
			break;
		case 4:
			calc_time(argv[1]);
			break;
		case 5:
			parse_input_level_order(argv[1], argv[2]);
			break;
		default:
			printf("Invalid option provided....\n");
			continue;
		}
	}
}