#include "parser.h"
#include "lexer.h"
#include <time.h>


void parse_input_inorder(char* testCaseFile,char* createfile)
{
	Grammar* gm = initialize();
	gm = make_table("grammar.txt",gm);
	FirstAndFollow* firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm,firstFol);
	ParseTable* pt = initializeParseTable();
	populateParseTable(firstFol,gm,pt);
	ParseTree* pTree = parseInputSourceCode(testCaseFile,pt,gm,firstFol);
	// printParseTree(pTree->root);
	printParseTree_inorder(pTree->root,createfile);
}


void parse_input_level_order(char* testCaseFile,char* createfile)
{
	Grammar* gm = initialize();
	gm = make_table("grammar.txt",gm);
	FirstAndFollow* firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm,firstFol);
	ParseTable* pt = initializeParseTable();
	populateParseTable(firstFol,gm,pt);
	ParseTree* pTree = parseInputSourceCode(testCaseFile,pt,gm,firstFol);
	printParseTree_levelOrder(pTree->root,createfile);

}

void calc_time(char *testCaseFile)
{
	clock_t start_time, end_time;

    double total_CPU_time, total_CPU_time_in_seconds;

    start_time = clock();

 	printf("%lf\n", (double)start_time);
    Grammar* gm = initialize();
	gm = make_table("grammar.txt",gm);
	FirstAndFollow* firstFol = initializeFirstFollow();
	ComputeFirstAndFollowSets(gm,firstFol);
	ParseTable* pt = initializeParseTable();
	populateParseTable(firstFol,gm,pt);
	ParseTree* pTree = parseInputSourceCode(testCaseFile,pt,gm,firstFol);

	end_time = clock();


	printf("%lf\n", (double)end_time);
	total_CPU_time = (double)(end_time - start_time);

    total_CPU_time_in_seconds =   total_CPU_time / (double)CLOCKS_PER_SEC;

    printf("Total CPU time -- %lf\nTotal CPU time in seconds -- %lf \n", total_CPU_time,total_CPU_time_in_seconds);
}



int main(int argc, char* argv[])
{
	printf("FIRST and FOLLOW set automated\n");
	printf("Both lexical and syntax analysis modules implemented\n");
	printf("Parse Tree constructed for syntatically correct code\n");
	printf("Parse tree printing is implemented using both Inorder and Level Order Traversal\n");
	printf("Modules work with all the provided testcases including the syntatically incorrect one\n");

	while(1)
	{
		printf("Press 0 to exit.\n");
		printf("Press 1 to get the comment free code.\n");
		printf("Press 2 to get the token list generated by lexer.\n");
		printf("Press 3 to get the Parse tree in Inorder \n");
		printf("Press 4 to get the Total time elapsed for syntax analysis\n");
		printf("Press 5 to get the Parse tree in Level Order\n");
		int option;
		scanf("%d",&option);

		switch(option)
		{
			case 0:
				exit(0);
				break;
			case 1: 
				removeComments(argv[1]);
				break;
			case 2:
				printTokens(argv[1]);
				break;
			case 3:
				parse_input_inorder(argv[1],argv[2]);
    			break;
    		case 4:
    			calc_time(argv[1]);
    			break;
    		case 5:
    			parse_input_level_order(argv[1],argv[2]);
    			break;
    		default:
    			printf("Invalid option provided\n");
    			continue;
		}
	}
	
}